document.getElementById("preloader-car").style.backgroundImage="url('images/car.png')";
document.getElementById("preloader-car").style.backgroundRepeat="no-repeat";
document.getElementById("preloader-car").style.backgroundSize="338px 96px";
document.getElementById("preloader-car").style.width="338px";
document.getElementById("preloader-car").style.height="96px";
document.getElementById("preloader-flower").style.backgroundImage="url('images/flower.png')";
document.getElementById("preloader-flower").style.backgroundRepeat="no-repeat";
document.getElementById("preloader-flower").style.backgroundSize="320px 386px";
document.getElementById("preloader-flower").style.width="320px";
document.getElementById("preloader-flower").style.height="386px";
document.getElementById("preloader-buzzsaw").style.backgroundImage="url('images/buzzsaw.png')";
document.getElementById("preloader-buzzsaw").style.backgroundRepeat="no-repeat";
document.getElementById("preloader-buzzsaw").style.backgroundSize="386px 386px";
document.getElementById("preloader-buzzsaw").style.width="386px";
document.getElementById("preloader-buzzsaw").style.height="386px";
document.getElementById("preloader-grinder").style.backgroundImage="url('images/grinder.png')";
document.getElementById("preloader-grinder").style.backgroundRepeat="no-repeat";
document.getElementById("preloader-grinder").style.backgroundSize="523px 168px";
document.getElementById("preloader-grinder").style.width="523px";
document.getElementById("preloader-grinder").style.height="168px";
document.getElementById("preloader-grinder").innerHTML="<img id='grinderwheel' src='images/anglegrinderwheel.png'><img id='sparx' src='images/sparks.gif'>";
document.getElementById("preloader-car").innerHTML="<img class='wheel1' src='images/wheel.png'><img class='wheel2' src='images/wheel.png'>";